// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Borc.DataMapper.Domain.Entities;

public partial class MapperContext : DbContext
{
    public MapperContext(DbContextOptions<MapperContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DataRecord> DataRecords { get; set; }

    public virtual DbSet<DataSource> DataSources { get; set; }

    public virtual DbSet<ImportBatch> ImportBatches { get; set; }

    public virtual DbSet<ImportRow> ImportRows { get; set; }

    public virtual DbSet<MappingProfile> MappingProfiles { get; set; }

    public virtual DbSet<MappingRule> MappingRules { get; set; }

    public virtual DbSet<PredefinedRegex> PredefinedRegexes { get; set; }

    public virtual DbSet<Template> Templates { get; set; }

    public virtual DbSet<TemplateField> TemplateFields { get; set; }

    public virtual DbSet<TemplateFieldAlias> TemplateFieldAliases { get; set; }

    public virtual DbSet<TemplateLayout> TemplateLayouts { get; set; }

    public virtual DbSet<TemplateVersion> TemplateVersions { get; set; }

    public virtual DbSet<VwTemplateCurrentVersion> VwTemplateCurrentVersions { get; set; }

    public virtual DbSet<VwTemplateField> VwTemplateFields { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_100_CI_AI_SC");

        modelBuilder.Entity<DataRecord>(entity =>
        {
            entity.ToTable("DataRecord");

            entity.HasIndex(e => e.ImportBatchId, "IX_DataRecord_ImportBatch").HasFilter("([ImportBatchId] IS NOT NULL)");

            entity.HasIndex(e => new { e.TemplateVersionId, e.CreatedAt }, "IX_DataRecord_TemplateVersion_Created").IsDescending(false, true);

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DataJson).IsRequired();
            entity.Property(e => e.SourceType).HasDefaultValue((short)1);
            entity.Property(e => e.UpdatedAt).HasPrecision(3);

            entity.HasOne(d => d.ImportBatch).WithMany(p => p.DataRecords)
                .HasForeignKey(d => d.ImportBatchId)
                .HasConstraintName("FK_DataRecord_ImportBatch");

            entity.HasOne(d => d.ImportRow).WithMany(p => p.DataRecords)
                .HasForeignKey(d => d.ImportRowId)
                .HasConstraintName("FK_DataRecord_ImportRow");

            entity.HasOne(d => d.Template).WithMany(p => p.DataRecords)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataRecord_Template");

            entity.HasOne(d => d.TemplateVersion).WithMany(p => p.DataRecords)
                .HasForeignKey(d => d.TemplateVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataRecord_TemplateVersion");
        });

        modelBuilder.Entity<DataSource>(entity =>
        {
            entity.ToTable("DataSource");

            entity.HasIndex(e => e.Code, "UQ_DataSource_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.UpdatedAt).HasPrecision(3);
        });

        modelBuilder.Entity<ImportBatch>(entity =>
        {
            entity.ToTable("ImportBatch");

            entity.HasIndex(e => new { e.TemplateVersionId, e.CreatedAt }, "IX_ImportBatch_TemplateVersion_Created").IsDescending(false, true);

            entity.Property(e => e.CompletedAt).HasPrecision(3);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FileHash)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.StartedAt).HasPrecision(3);
            entity.Property(e => e.Status).HasDefaultValue((short)1);

            entity.HasOne(d => d.MappingProfile).WithMany(p => p.ImportBatches)
                .HasForeignKey(d => d.MappingProfileId)
                .HasConstraintName("FK_ImportBatch_MappingProfile");

            entity.HasOne(d => d.TemplateVersion).WithMany(p => p.ImportBatches)
                .HasForeignKey(d => d.TemplateVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ImportBatch_TemplateVersion");
        });

        modelBuilder.Entity<ImportRow>(entity =>
        {
            entity.ToTable("ImportRow");

            entity.HasIndex(e => new { e.ImportBatchId, e.Status }, "IX_ImportRow_Batch_Status");

            entity.HasIndex(e => new { e.ImportBatchId, e.RowNumber }, "UQ_ImportRow_Batch_Row").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.RawDataJson).IsRequired();
            entity.Property(e => e.Status).HasDefaultValue((short)1);

            entity.HasOne(d => d.ImportBatch).WithMany(p => p.ImportRows)
                .HasForeignKey(d => d.ImportBatchId)
                .HasConstraintName("FK_ImportRow_ImportBatch");
        });

        modelBuilder.Entity<MappingProfile>(entity =>
        {
            entity.ToTable("MappingProfile");

            entity.HasIndex(e => e.TemplateVersionId, "IX_MappingProfile_TemplateVersion");

            entity.HasIndex(e => new { e.TemplateVersionId, e.Name }, "UQ_MappingProfile_TemplateVersion_Name").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.SourceType).HasDefaultValue((short)1);
            entity.Property(e => e.Status).HasDefaultValue((short)1);
            entity.Property(e => e.UpdatedAt).HasPrecision(3);

            entity.HasOne(d => d.TemplateVersion).WithMany(p => p.MappingProfiles)
                .HasForeignKey(d => d.TemplateVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MappingProfile_TemplateVersion");
        });

        modelBuilder.Entity<MappingRule>(entity =>
        {
            entity.ToTable("MappingRule");

            entity.HasIndex(e => e.MappingProfileId, "IX_MappingRule_Profile");

            entity.HasIndex(e => e.TargetFieldId, "IX_MappingRule_TargetField");

            entity.HasIndex(e => new { e.MappingProfileId, e.SourceColumn }, "UQ_MappingRule_Profile_Source").IsUnique();

            entity.Property(e => e.Confidence).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.NormalizedSourceColumn)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.SourceColumn)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.MappingProfile).WithMany(p => p.MappingRules)
                .HasForeignKey(d => d.MappingProfileId)
                .HasConstraintName("FK_MappingRule_MappingProfile");

            entity.HasOne(d => d.TargetField).WithMany(p => p.MappingRules)
                .HasForeignKey(d => d.TargetFieldId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MappingRule_TargetField");
        });

        modelBuilder.Entity<PredefinedRegex>(entity =>
        {
            entity.ToTable("PredefinedRegex");

            entity.HasIndex(e => e.Code, "UQ_PredefinedRegex_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Pattern)
                .IsRequired()
                .HasMaxLength(1000);
        });

        modelBuilder.Entity<Template>(entity =>
        {
            entity.ToTable("Template");

            entity.HasIndex(e => e.Status, "IX_Template_Status");

            entity.HasIndex(e => e.Code, "UQ_Template_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Status).HasDefaultValue((short)1);
            entity.Property(e => e.UpdatedAt).HasPrecision(3);
        });

        modelBuilder.Entity<TemplateField>(entity =>
        {
            entity.ToTable("TemplateField");

            entity.HasIndex(e => e.DataSourceId, "IX_TemplateField_DataSource").HasFilter("([DataSourceId] IS NOT NULL)");

            entity.HasIndex(e => new { e.TemplateVersionId, e.SortOrder }, "IX_TemplateField_Version_Sort");

            entity.HasIndex(e => new { e.TemplateVersionId, e.FieldKey }, "UQ_TemplateField_Version_Key").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DataType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.DbType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.DefaultValue).HasMaxLength(2000);
            entity.Property(e => e.FieldKey)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Regex).HasMaxLength(1000);
            entity.Property(e => e.UpdatedAt).HasPrecision(3);

            entity.HasOne(d => d.DataSource).WithMany(p => p.TemplateFields)
                .HasForeignKey(d => d.DataSourceId)
                .HasConstraintName("FK_TemplateField_DataSource");

            entity.HasOne(d => d.TemplateVersion).WithMany(p => p.TemplateFields)
                .HasForeignKey(d => d.TemplateVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplateField_TemplateVersion");
        });

        modelBuilder.Entity<TemplateFieldAlias>(entity =>
        {
            entity.ToTable("TemplateFieldAlias");

            entity.HasIndex(e => e.NormalizedAlias, "IX_TemplateFieldAlias_Normalized");

            entity.HasIndex(e => new { e.TemplateFieldId, e.NormalizedAlias }, "UQ_TemplateFieldAlias_Field_Alias").IsUnique();

            entity.Property(e => e.Alias)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.NormalizedAlias)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.TemplateField).WithMany(p => p.TemplateFieldAliases)
                .HasForeignKey(d => d.TemplateFieldId)
                .HasConstraintName("FK_TemplateFieldAlias_TemplateField");
        });

        modelBuilder.Entity<TemplateLayout>(entity =>
        {
            entity.ToTable("TemplateLayout");

            entity.HasIndex(e => new { e.TemplateVersionId, e.VersionNo }, "UQ_TemplateLayout_Version").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsPublished).HasDefaultValue(true);
            entity.Property(e => e.LayoutJson).IsRequired();
            entity.Property(e => e.UpdatedAt).HasPrecision(3);
            entity.Property(e => e.VersionNo).HasDefaultValue(1);

            entity.HasOne(d => d.TemplateVersion).WithMany(p => p.TemplateLayouts)
                .HasForeignKey(d => d.TemplateVersionId)
                .HasConstraintName("FK_TemplateLayout_TemplateVersion");
        });

        modelBuilder.Entity<TemplateVersion>(entity =>
        {
            entity.ToTable("TemplateVersion");

            entity.HasIndex(e => new { e.TemplateId, e.VersionNo }, "IX_TemplateVersion_Template").IsDescending(false, true);

            entity.HasIndex(e => new { e.TemplateId, e.VersionNo }, "UQ_TemplateVersion_Template_Version").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.PublishedAt).HasPrecision(3);
            entity.Property(e => e.Status).HasDefaultValue((short)1);

            entity.HasOne(d => d.Template).WithMany(p => p.TemplateVersions)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplateVersion_Template");
        });

        modelBuilder.Entity<VwTemplateCurrentVersion>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_TemplateCurrentVersion");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<VwTemplateField>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_TemplateFields");

            entity.Property(e => e.DataType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.DbType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.DefaultValue).HasMaxLength(2000);
            entity.Property(e => e.FieldKey)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Regex).HasMaxLength(1000);
            entity.Property(e => e.TemplateCode)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TemplateName)
                .IsRequired()
                .HasMaxLength(250);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}