// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class DataSource
{
    public long Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public short SourceType { get; set; }

    public string ConfigJson { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public long? UpdatedBy { get; set; }

    public virtual ICollection<TemplateField> TemplateFields { get; set; } = new List<TemplateField>();
}