// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class DataRecord
{
    public long Id { get; set; }

    public long TemplateId { get; set; }

    public long TemplateVersionId { get; set; }

    public string DataJson { get; set; }

    public short SourceType { get; set; }

    public long? ImportBatchId { get; set; }

    public long? ImportRowId { get; set; }

    public DateTime CreatedAt { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public long? UpdatedBy { get; set; }

    public virtual ImportBatch ImportBatch { get; set; }

    public virtual ImportRow ImportRow { get; set; }

    public virtual Template Template { get; set; }

    public virtual TemplateVersion TemplateVersion { get; set; }
}