// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class ImportRow
{
    public long Id { get; set; }

    public long ImportBatchId { get; set; }

    public int RowNumber { get; set; }

    public string RawDataJson { get; set; }

    public string MappedDataJson { get; set; }

    public short Status { get; set; }

    public int ErrorCount { get; set; }

    public string ErrorJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<DataRecord> DataRecords { get; set; } = new List<DataRecord>();

    public virtual ImportBatch ImportBatch { get; set; }
}