// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class ImportBatch
{
    public long Id { get; set; }

    public long TemplateVersionId { get; set; }

    public long? MappingProfileId { get; set; }

    public string FileName { get; set; }

    public string FileHash { get; set; }

    public long? FileSize { get; set; }

    public int TotalRows { get; set; }

    public int ValidRows { get; set; }

    public int InvalidRows { get; set; }

    public short Status { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public long? CreatedBy { get; set; }

    public virtual ICollection<DataRecord> DataRecords { get; set; } = new List<DataRecord>();

    public virtual ICollection<ImportRow> ImportRows { get; set; } = new List<ImportRow>();

    public virtual MappingProfile MappingProfile { get; set; }

    public virtual TemplateVersion TemplateVersion { get; set; }
}