// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class MappingRule
{
    public long Id { get; set; }

    public long MappingProfileId { get; set; }

    public string SourceColumn { get; set; }

    public string NormalizedSourceColumn { get; set; }

    public long TargetFieldId { get; set; }

    public short MappingMethod { get; set; }

    public decimal? Confidence { get; set; }

    public string TransformJson { get; set; }

    public string ValidationJson { get; set; }

    public int SortOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public long? CreatedBy { get; set; }

    public virtual MappingProfile MappingProfile { get; set; }

    public virtual TemplateField TargetField { get; set; }
}