// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class MappingProfile
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long TemplateVersionId { get; set; }

    public short SourceType { get; set; }

    public short Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public long? UpdatedBy { get; set; }

    public virtual ICollection<ImportBatch> ImportBatches { get; set; } = new List<ImportBatch>();

    public virtual ICollection<MappingRule> MappingRules { get; set; } = new List<MappingRule>();

    public virtual TemplateVersion TemplateVersion { get; set; }
}