// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Borc.DataMapper.Domain.Common;
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class Template : EntityBase
{

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public short Status { get; set; }


    public virtual ICollection<DataRecord> DataRecords { get; set; } = new List<DataRecord>();

    public virtual ICollection<TemplateVersion> TemplateVersions { get; set; } = new List<TemplateVersion>();
}