// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class TemplateLayout
{
    public long Id { get; set; }

    public long TemplateVersionId { get; set; }

    public int VersionNo { get; set; }

    public string LayoutJson { get; set; }

    public bool IsPublished { get; set; }

    public DateTime CreatedAt { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public long? UpdatedBy { get; set; }

    public virtual TemplateVersion TemplateVersion { get; set; }
}