// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class TemplateVersion
{
    public long Id { get; set; }

    public long TemplateId { get; set; }

    public int VersionNo { get; set; }

    public short Status { get; set; }

    public string SchemaJson { get; set; }

    public bool IsPublished { get; set; }

    public DateTime CreatedAt { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? PublishedAt { get; set; }

    public long? PublishedBy { get; set; }

    public virtual ICollection<DataRecord> DataRecords { get; set; } = new List<DataRecord>();

    public virtual ICollection<ImportBatch> ImportBatches { get; set; } = new List<ImportBatch>();

    public virtual ICollection<MappingProfile> MappingProfiles { get; set; } = new List<MappingProfile>();

    public virtual Template Template { get; set; }

    public virtual ICollection<TemplateField> TemplateFields { get; set; } = new List<TemplateField>();

    public virtual ICollection<TemplateLayout> TemplateLayouts { get; set; } = new List<TemplateLayout>();
}