// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class TemplateFieldAlias
{
    public long Id { get; set; }

    public long TemplateFieldId { get; set; }

    public string Alias { get; set; }

    public string NormalizedAlias { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual TemplateField TemplateField { get; set; }
}