// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class VwTemplateCurrentVersion
{
    public long TemplateId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public long TemplateVersionId { get; set; }

    public int VersionNo { get; set; }

    public short Status { get; set; }

    public bool IsPublished { get; set; }
}