// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borc.DataMapper.Domain.Entities;

public partial class VwTemplateField
{
    public long TemplateId { get; set; }

    public string TemplateCode { get; set; }

    public string TemplateName { get; set; }

    public long TemplateVersionId { get; set; }

    public int VersionNo { get; set; }

    public long FieldId { get; set; }

    public string FieldKey { get; set; }

    public string Label { get; set; }

    public string DataType { get; set; }

    public string DbType { get; set; }

    public int? Length { get; set; }

    public byte? Precision { get; set; }

    public byte? Scale { get; set; }

    public bool IsRequired { get; set; }

    public string Regex { get; set; }

    public string DefaultValue { get; set; }

    public long? DataSourceId { get; set; }

    public int SortOrder { get; set; }

    public string ConfigJson { get; set; }
}