<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Borc.DataMapper.Application\Borc.DataMapper.Application.csproj" />
		<ProjectReference Include="..\Borc.DataMapper.Domain\Borc.DataMapper.Domain.csproj" />
	</ItemGroup>

</Project>
